install:
  # Download the Rust and Cargo installer.
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-stable-x86_64-pc-windows-gnu.msi"

  # Install Rust and Cargo and wait for installation to finish by using Write-Output.
  - ps: msiexec /package "rust-stable-x86_64-pc-windows-gnu.msi" /quiet /norestart | Write-Output

  # Pick up the new Path variable after the installer modified it.
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")

  # Print versions for future reference.
  - rustc --version
  - cargo --version

build_script:
  - C:\msys64\usr\bin\sh.exe --login /c/projects/pris/build_msys.sh
