install:
  # Download the Rust and Cargo installer.
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.17.0-x86_64-pc-windows-gnu.msi"

  # Install Rust and Cargo and wait for installation to finish by using Write-Output.
  - ps: msiexec /package "rust-1.17.0-x86_64-pc-windows-gnu.msi" /quiet /norestart | Write-Output

  # Pick up the new Path variable after the installer modified it.
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")

  # Print versions for future reference.
  - rustc --version
  - cargo --version

build_script:
  # The MSYS shell will cd to $HOME when it starts. But we want to stay in the
  # current working directory. So set home to here. Also, we must set MSYSTEM to
  # get MSYS64. Without this the value of PKG_CONFIG_PATH (which is set by
  # sh.exe when it executes /etc/profile due to --login) does not point to the
  # directories where the mingw-w64-x86_64-* packages store their info.
  - ps: $env:HOME = (Get-Location).path
  - ps: $env:MSYSTEM = "MINGW64"
  - C:\msys64\usr\bin\sh.exe --login /c/projects/pris/build_msys.sh
