language: rust

addons:
  apt:
    packages:
      - fonts-cantarell
      - libcairo2-dev

rust:
  - 1.13.0
  - 1.14.0
  - 1.15.1
  - beta
  - nightly

script:
  - cargo build
  - cargo test
  - tests/compile_examples.py
