language: rust

rust:
  - 1.13.0
  - 1.14.0
  - 1.15.1
  - 1.16.0
  - beta
  - nightly

os:
  - linux
  - osx

# Apparently there is no libharfbuzz-dev package for ancient Ubuntu 12.04, opt
# for the slightly less ancient 14.04 image.
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - fonts-cantarell
      - libcairo2-dev
      - libharfbuzz-dev
      - librsvg2-dev

script:
  - cargo build
  - cargo test
  - tests/compile_examples.py
