[package]
name    = "pris"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies]
docopt          = "0.7"  # TODO: Upgrade to 0.8 too.
freetype-rs     = "0.11"
rustc-serialize = "0.3"
